// webpack5/进阶/webpack devServer/src/App.jsx
import React, { Component } from "react";
import About from "./component/About.jsx";
import New from "./component/New.jsx";

class App extends Component {
  constructor(props) {
    super(props);
  }
  state = {
    message: "Hello React",
  };

  render() {
    return (
      <div style={{ color: "red", fontSize: 20, fontWeight: "bold" }}>
        {this.state.message}
        <About />
        <New />
      </div>
    );
  }
}
export default App;

// webpack5/进阶/webpack devServer/src/App.vue
<template>
  <div id="app">
    <div>
      {{message}}
    </div>
    <About/>
    <New/>
  </div>
</template>
<script>
 import About from "./component/About.vue";
 import New from "./component/New.vue";
 export default {
   components: {New, About},
   data() {
     return {
       message: "Hello Vue"
     }
   }
 }
</script>
<style lang="less">
#app{
  font-size: 20px;
  color: rebeccapurple;
  font-weight: bold;
}
</style>
